# Generated by Django 4.1.3 on 2023-01-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_watchlist_date_added_alter_portfolio_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='date_added',
            field=models.DateField(),
        ),
    ]
