# Generated by Django 4.1.3 on 2023-01-28 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_alter_price_date_alter_watchlist_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='view_count',
        ),
        migrations.AlterField(
            model_name='price',
            name='date',
            field=models.DateField(blank=True, default='1991-01-01', null=True, verbose_name='YYYY-MM-DD'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='date_added',
            field=models.DateField(verbose_name='YYYY-MM-DD'),
        ),
    ]
