# Generated by Django 4.1.3 on 2023-02-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_remove_portfolio_view_count_alter_price_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='date',
            field=models.DateField(blank=True, default='1991-01-01', null=True, verbose_name='%Y-%m-%d'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='date_added',
            field=models.DateField(verbose_name='%Y-%m-%d'),
        ),
    ]
