# Generated by Django 4.1.3 on 2023-02-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateField(verbose_name='%Y-%m-%d'),
        ),
    ]
