# Generated by Django 4.1.3 on 2023-03-01 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_piece_pieceparticipation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pieceparticipation',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='pieceparticipation',
            old_name='piece_id',
            new_name='piece',
        ),
    ]
