# Generated by Django 4.1.3 on 2023-03-01 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_rename_item_id_pieceparticipation_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetParticipation',
            fields=[
                ('participation', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='App.item')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set', to='App.item')),
            ],
        ),
    ]
