# Generated by Django 4.1.3 on 2023-03-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_setparticipation'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='type',
            field=models.CharField(choices=[('MINIFIG', 'MINIFIG'), ('PART', 'PART'), ('SET', 'SET'), ('GEAR', 'GEAR'), ('CATALOG', 'CATALOG'), ('INSTRUCTION', 'INSTRUCTION'), ('UNSORTED_LOT', 'UNSORTED_LOT'), ('ORIGINAL_BOX', 'ORIGINAL_BOX')], default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pieceparticipation',
            name='colour',
            field=models.CharField(default=None, max_length=40),
            preserve_default=False,
        ),
    ]
