# Generated by Django 4.1.3 on 2023-03-01 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_piece_type_pieceparticipation_colour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='piece',
            old_name='piece',
            new_name='piece_id',
        ),
    ]
