# Generated by Django 4.1.3 on 2023-03-01 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_rename_piece_piece_piece_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pieceparticipation',
            old_name='colour',
            new_name='colour_id',
        ),
    ]
