# Generated by Django 4.1.3 on 2023-03-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0018_rename_colour_pieceparticipation_colour_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='piece_name',
            field=models.CharField(max_length=360),
        ),
    ]
