# Generated by Django 4.1.3 on 2023-03-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0019_alter_piece_piece_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='bought_for',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='date_sold',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='sold_for',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
