# Generated by Django 4.1.3 on 2023-03-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0020_portfolio_bought_for_portfolio_date_sold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='date_sold',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='sold_for',
            field=models.FloatField(null=True),
        ),
    ]
