# Generated by Django 4.1.3 on 2023-03-06 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0021_alter_portfolio_date_sold_alter_portfolio_sold_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='date_sold',
            field=models.DateField(null=True),
        ),
    ]
