# Generated by Django 4.1.3 on 2023-03-06 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0022_alter_portfolio_date_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='date_added',
            field=models.DateField(),
        ),
    ]
