# Generated by Django 4.1.3 on 2023-03-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0023_alter_portfolio_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='notes',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
