# Generated by Django 4.1.3 on 2023-03-07 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0024_portfolio_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='quantity',
        ),
    ]
