# Generated by Django 4.1.3 on 2023-03-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0025_remove_portfolio_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='date_added',
            field=models.DateField(verbose_name='%Y-%m-%d'),
        ),
    ]
