# Generated by Django 4.1.3 on 2023-03-12 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0026_alter_portfolio_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='bought_for',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='date_added',
            field=models.DateField(null=True, verbose_name='%Y-%m-%d'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='date_sold',
            field=models.DateField(null=True, verbose_name='%Y-%m-%d'),
        ),
    ]
