# Generated by Django 4.1.7 on 2023-03-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0027_alter_portfolio_bought_for_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateField(blank=True, null=True, verbose_name='%Y-%m-%d'),
        ),
    ]
