# Generated by Django 4.1.7 on 2023-03-23 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0029_alter_user_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
    ]
