# Generated by Django 4.1.7 on 2023-03-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0030_remove_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(max_length=200),
        ),
    ]
