# Generated by Django 4.1.7 on 2023-03-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0033_alter_item_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(max_length=210),
        ),
    ]
